# Configuration file for the feeding demo
#
# If not otherwise specified:
#     All units are metric.
#     This means all forces and torques are also in N and Nm.
#     All distances are in m.
#     All rotations are in radians.
#     All robot configurations specify 6 joint angles in a list
#     All transform use the format [x,y,z,rx,ry,rz] of positions and rotations in a list.
# 


# Visualization parameters
visualization:
  topicName: dart_markers/feeding
  baseFrameName: map

# Robot parameters
ada:
  urdfUri: package://ada_description/robots_urdf/ada_with_camera_forque.urdf
  srdfUri: package://ada_description/robots_urdf/ada_with_camera_forque.srdf
  endEffectorName: j2n6s200_forque_end_effector
  homeConfiguration: [3.89015, 3.34645, 2.28738, -1.39666, 2.96761, 2.49281]      # the start configuration of the robot joints
  baseFramePose: [0.7, -0.1, -0.27, 0, 0, 3.1415]                                 # the transform between the robot base and the left front corner of the table

# Workspace parameters
plate:
  urdfUri: package://pr_ordata/data/objects/plate.urdf
  pose: [.495, 0.19, 0.0, 0, 0, 0]
table:
  urdfUri: package://pr_ordata/data/furniture/table_feeding.urdf
  pose: [0.76, 0.38, -0.735, 0, 0, 0]
  #pose: [0.74, 0.40, -0.72, 0, 0, 0]
defaultFoodItem:
  urdfUri: package://pr_ordata/data/objects/food_item.urdf
  pose: [.495, 0.19, 0.00, 0, 0, 0]
person: # the mannequin
  urdfUri: package://pr_ordata/data/objects/tom.urdf
  pose: [0.425, -0.45, 0.502, 0, 0, 3.1415]
  #pose: [0.425, -0.45, 0.472, 0, 0, 3.1415]
workspaceEnvironment:
  urdfUri: package://pr_ordata/data/furniture/workspace_feeding_demo.urdf
  pose: [0, 0, 0, 0, 0, 0]
wheelchair:
  urdfUri: package://pr_ordata/data/furniture/wheelchair.urdf
  pose: [0, 0, 0, 0, 0, 0]

# Feeding demo movement parameters
feedingDemo:
  heightAbovePlate: 0.11
  heightAboveFood: 0.09
  heightIntoFood: 0.02           # the real robot plans *below* the food. This parameter specifies how far
  distanceToPerson: 0.25
  distanceFromPerson: 0.15
  waitMillisecsAtFood: 1000     # short pause after skewering the food
  waitMillisecsAtPerson: 5000   # long pause so person can take a bite

# Planning parameters
planning:
  maxNumberOfTrials: 1
  timeoutSeconds: 2
  tsr:
    horizontalToleranceAbovePlate: 0.005
    verticalToleranceAbovePlate: 0.002
    horizontalToleranceNearFood: 0.002
    verticalToleranceNearFood: 0.001
    horizontalToleranceNearPerson: 0.01
    verticalToleranceNearPerson: 0.005
  endEffectorOffset:
    positionTolerance: 0.002
    angularTolerance: 0.04

# Parameters for the F/T sensor and the MoveUntilTouchController
ftSensor:
  controllerFTThresholdTopic: /move_until_touch_topic_controller/set_forcetorque_threshold/
  ftTopic: /forque/forqueSensor
  thresholds:
    standard:       # used when no other thresholds are specified
      force: 2
      torque: 2
    grabFood:       # active when going down to grab the food
      force: 22
      torque: 2
    afterGrabFood:  # active when going up after food has been grabbed
      force: 50
      torque: 2

# Perception parameters
perception:
  detectorDataUri: package://pr_ordata/data/objects/tag_data_foods.json
  foodDetectorTopicName: /deep_pose/marker_array
  faceDetectorTopicName: /face_pose
  referenceFrameName: j2n6s200_link_base
  timeoutSeconds: 5
  foodName: cherry tomato
  faceName: mouth

foodItems:
  # names: ["apricot", "apple", "cantaloupe", "egg", "bell_pepper", "cherry_tomato", "banana", "carrot", "grape_green", "watermelon", "blackberry", "celery", "strawberry", "broccoli", "cauliflower"]
  # forces: [25,       11.75,     7.37,        4.67,  20.99,        11.36,            6.13,       22.49,      9.07,       5.21,          5.98,        17.48,      6.63,         21.63,    21.63]
  
  # bite acquistion
  # names: ["cantaloupe", "egg",  "banana", "carrot", "celery", "strawberry"]
  # forces: [15,        15,     15,      22.49,  17.48,       15]

  # bite transfer
  names: ["cantaloupe", "egg",  "banana", "carrot", "celery", "strawberry"]
  forces: [15,        15,     15,      28,  17.48,       6]

study:
  skipSkewering: false
