# Configuration file for the feeding demo
#
# If not otherwise specified:
#     All units are metric.
#     All forces and torques are in N and Nm, respectively.
#     All distances are in m.
#     All rotations are in radians.
#     All robot configurations specify 6 joint angles in a list
#     All transform use the format [x,y,z,rx,ry,rz] of positions and rotations in a list.
#

# Visualization parameters
visualization:
  topicName: dart_markers/feeding
  baseFrameName: map

# Robot parameters
ada:
  urdfUri: package://ada_description/robots_urdf/ada_with_camera_forque.urdf
  srdfUri: package://ada_description/robots_urdf/ada_with_camera_forque.srdf
  endEffectorName: j2n6s200_forque_end_effector
  homeConfiguration: [3.89015, 3.34645, 2.28738, -1.39666, 2.96761, 2.49281]      # the start configuration of the robot joints
  baseFramePose: [0.7, -0.1, -0.25, 0, 0, 3.1415]                                 # the transform between the robot base and the left front corner of the table

# Workspace parameters
plate:
  urdfUri: package://pr_assets/data/objects/plate.urdf
  pose: [.445, 0.19, -0.02, 0, 0, 0]
table:
  urdfUri: package://pr_assets/data/furniture/table_feeding.urdf
  pose: [0.76, 0.38, -0.745, 0, 0, 0]
defaultFoodItem:
  urdfUri: package://pr_assets/data/objects/food_item.urdf
  pose: [.445, 0.19, 0.0, 3.1415, 0, 0]
person: # the mannequin
  urdfUri: package://pr_assets/data/objects/tom.urdf
  pose: [0.425, -0.45, 0.502, 0, 0, 3.1415]
workspaceEnvironment:
  urdfUri: package://pr_assets/data/furniture/workspace_feeding_demo.urdf
  pose: [0, 0, 0, 0, 0, 0]
wheelchair:
  urdfUri: package://pr_assets/data/furniture/wheelchair.urdf
  pose: [0.0, 0.0, 0, 0, 0, 0]

# Feeding demo movement parameters
feedingDemo:
  heightAbovePlate: 0.10
  heightAboveFood: 0.10
  heightIntoFood: 0.05           # the real robot plans *below* the food. This parameter specifies how far
  moveOutofFood: 0.01
  distanceToPerson: 0.25
  distanceFromPerson: 0.15
  waitMillisecsAtFood: 00     # short pause after skewering the food
  waitMillisecsAtPerson: 5000   # long pause so person can take a bite
  fixedFaceY: 0.23

# Planning parameters
planning:
  maxNumberOfTrials: 1
  timeoutSeconds: 2
  tsr:
    horizontalToleranceAbovePlate: 0.03
    verticalToleranceAbovePlate: 0.01
    rotationToleranceAbovePlate: 3.1416
    horizontalToleranceNearFood: 0.005
    verticalToleranceNearFood: 0.005
    rotationToleranceNearFood: 0.005
    horizontalToleranceNearPerson: 0.002
    verticalToleranceNearPerson: 0.002
    tiltToleranceNearFood: 0.0
  endEffectorOffset:
    positionTolerance: 0.00008
    angularTolerance: 0.004
  endEffectorTwist:
    positionTolerance: 0.0002
    angularTolerance: 0.004

# Parameters for the F/T sensor and the MoveUntilTouchController
ftSensor:
  controllerFTThresholdTopic: /move_until_touch_topic_controller/set_forcetorque_threshold/
  ftTopic: /forque/forqueSensor
  # ftTopic: /fingervision/fv_3_l/wrench
  thresholds:
    standard:       # used when no other thresholds are specified
      force: 3
      torque: 2
    grabFood:       # active when going down to grab the food
      force: 22
      torque: 2
    afterGrabFood:  # active when going up after food has been grabbed
      force: 50
      torque: 2

# Perception parameters
perception:
  detectorDataUri: package://pr_assets/data/objects/tag_data_foods.json
  foodDetectorTopicName: /deep_pose/marker_array
  faceDetectorTopicName: /face_pose/marker_array # TODO(GL): added marker_array
  referenceFrameName: j2n6s200_link_base
  timeoutSeconds: 5
  faceName: mouth

foodItems:
  # names: ["apricot", "apple", "cantaloupe", "egg", "bell_pepper", "cherry_tomato", "banana", "carrot", "grape_green", "watermelon", "blackberry", "celery", "strawberry", "broccoli", "cauliflower"]
  # forces: [25,       11.75,     7.37,        4.67,  20.99,        11.36,            6.13,       22.49,      9.07,       5.21,          5.98,        17.48,      6.63,         21.63,    21.63]
  names: ["cantaloupe", "egg",  "banana", "carrot", "celery", "strawberry", "melon"]
  forces: [10,3,3,7,22,10,7]
  pickUpAngleModes: [0, 2, 2, 0, 0, 1, 0]

rotationFree:
  names: ["cantaloupe", "banana", "melon"]

study:
  skipSkewering: false
  doForkPickup: false
  # y positive is closer to wheelchair
  # z
  forkHolderTranslation: [0.558, -0.023, 0.037]
  forkHolderAngle: 0.0

  # 0 straight
  # 1 strawberry-style
  # 2 banana-style
  pickupAngleMode: 0





  # x: from operator
  # y: towards user 0.24
  # z: up

  # 0.73
  personPose: [0.295, 0.24, 0.73, 0, 0, 3.1415]
  tiltOffset: [-0.04, 0, -0.04]
